language: android
android:
  components:
  - platform-tools
  - tools
  - build-tools-26.0.2
  - android-27

before_deploy: "echo 'ready?'"
deploy:
  provider: bintray
  file: descriptor.json
  user: rizafu
  on: master
  key:
    secure: T8ee32ouSdpaa1SU986A9klreyPTpEITrH8anXjf2l7e1E5oekE18htsiN7UPF8RIq1ZW/8MpnZdMlPk/6x0iKkcXVN059/DDf0/f4J+xgln8YCvHYAoIIJHZ8i2OmrOYFUZB5GMjNqvWQ/40f9ATL8ZuZIMWOaiPhSkcEuRlhDH3527jSVzGifc7k9bxfyLG9GLN48NNtGmK9jyRfxff8S8BHObgj3zm/jOhIlWSuMjBb/ARbikFn571FdL+kJW4CCiYQmdwSWnfG4J6bLtUhQ6Zw6xzY5vlH0MY/kDfixbh6xOCtYtfNf7n9fe5rcQ+pyRZLhV3hdp8byM4RckqTE7FZFpDdUV1G9O79VY3te3iYBajYdQzJVGvhABfgPJRlIGAyiKIRqmb6vCE2zwQ4xI3GwJCZEix6xReGlLJGz1kLafB1xD6F1OSrHpoDbKgPY715ZWjUqa6n5zBkMGWGE5vJpl1i822gUHYa63XWSHBbMlBSR7wx32lK+PQAxHzDUWm9l28G0P+Zc0Ac6YDOPneeC7Jl+Mr+05HK67DhbhUEoqrlTcrSSmrmGyqSpbOOnvQ8axy/+qcQS1gSBsgfOVIH4bK+FJmjhXY98etNGdQrCPJuOj5EiOzauv1d3swddzN3gRTEmxmyjsiuPdsBHg/wOj7LKBuvG20PHvGbI=